### ISSUE TITLE
Gauge should accept integer values instead of double

### ISSUE THREAD

**Issue by mariuszwojcik** [Pereingo/statsd-csharp-client#36]
Hi,

   I have noticed that Gauge is accepting and sends *double* values which are not accepted by the Jroland/StatsdNet service. For it to work with the service, the value should be an integer.

**Comment by DarrellMozingo** [comment]
Looks like it was changed to doubles in https://github.com/goncalopereira/statsd-csharp-client/commit/0c317d542505c8fee6257888a7df104924165b77. Do you remember why @goncalopereira?

**Comment by DarrellMozingo** [comment]
So the "official" [statsd spec](https://github.com/b/statsd_spec) says "Most implementations store values internally as a IEEE 754 double precision float, but many implementations and graphing systems only support integer values." Whisper seems to [store as float](http://graphite.readthedocs.org/en/latest/whisper.html), and statsd seems to [support floats](https://github.com/etsy/statsd/blob/d7b31bf70da865a70f29d011b4e6d0b9f70f6ce1/stats.js#L264), so I think a double is probably a better option here over an int/long. Maybe decimal. Either way I haven't had any more requests so going to close this issue.
