### ISSUE TITLE
Cannot handle address family 49744

### ISSUE THREAD

**Issue by saper** [Pereingo/statsd-csharp-client#45]
On many modern UNIX systems `localhost` has both IPv4 (127.0.0.1) and IPv6 (::1) entries.

Therefore simple setting `StatsdServerName = "localhost"` fails with:

```
Cannot handle address family 49744
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Net.Dns.GetHostByName_internal (string,string&,string[]&,string[]&) <0xffffffff>
  at System.Net.Dns.GetHostByName (string) <0x0004d>
  at System.Net.Dns.GetHostEntry (string) <0x000a5>
  at StatsdClient.StatsdUDP.GetIpv4Address (string) <0x0004f>
  at StatsdClient.StatsdUDP..ctor (string,int,int) <0x000f1>
  at StatsdClient.Metrics.CreateStatsD (StatsdClient.MetricsConfig) <0x000e5>
  at StatsdClient.Metrics.Configure (StatsdClient.MetricsConfig) <0x000c7>
```

Environment: recent Mono (4.3.0 built from git, @jpasichnyk reports that for Mono 4.0.1 as well)

**Comment by saper** [comment]
(closing for now as we have trouble reproducing this again)

**Comment by saper** [comment]
Minimal case:

https://gist.github.com/jpasichnyk/e4bca663138cad192881

Strace output:

https://gist.github.com/jpasichnyk/06d047f61eb8246ff469

**Comment by DarrellMozingo** [comment]
Hey saper!

Other than the tests, why are you using localhost for the server? If it's really needed, does 127.0.0.1 work as an alternative?

We haven't used mono in production for a while now (for issues like this with too many frameworks!). If you need a fix, any chance you'd want to take a stab at it?

**Comment by saper** [comment]
It's actually  @jpasichnyk reporting (on IRC:) but it looks like some lower-level problem with `getaddrinfo(3)` or name server caching/whatever. I can't reproduce this on FreeBSD (i.e. I always keep getting `127.0.0.1` returned). I think even `::1` works instead of localhost. 

I am documenting this issue here in case somebody has the same issue; right now I find it not good that   IPv6 is not supported (could be a separate issue:) but let's find out if this is a `statsd-csharp-client` problem, `mono` problem or maybe Ubuntu issue.

**Comment by saper** [comment]
strace without nscd running:

https://gist.github.com/jpasichnyk/84f2c262f5bb26ca75d5

Killing nscd seems to fix the problem :/ Running nscd `2.19-0ubuntu6.6`

**Comment by saper** [comment]
`strace -x -e read=5 -e write=5` without nscd:

https://gist.github.com/jpasichnyk/468627eb1e844afcdeab

`strace -x -e read=5 -e write=5` without nscd:

https://gist.github.com/jpasichnyk/83c1e0b963bfbb064cb6

**Comment by DarrellMozingo** [comment]
Closing this as there might be work arounds, and with .NET Core out (thought support for this client forthcoming) it seems not worth it to pursue mono bugs. Thanks for reporting and following up on it though, very much appreciated :)
