### ISSUE TITLE
Support for .Net CoreClr

### ISSUE THREAD

**Issue by hjgraca** [Pereingo/statsd-csharp-client#48]
Hi,

Is it in the roadmap support/upgrade to .net coreclr?
Thanks.

**Comment by DarrellMozingo** [comment]
Hi there Henrique,

No immediate plans. Haven't had a chance to play with CoreCLR yet actually. Did you get any errors or weird behaviour when you tried?

Thanks!

**Comment by bilal-fazlani** [comment]
I have migrated this library to core clr and created a pull request
https://github.com/Pereingo/statsd-csharp-client/pull/56

**Comment by wjdavis5** [comment]
+1

**Comment by TerribleDev** [comment]
#65

**Comment by DarrellMozingo** [comment]
Whoops, meant to close the other PR :)

**Comment by DarrellMozingo** [comment]
Supported (via .net standard 1.3) as of version 2.0.68 on NuGet.
