### ISSUE TITLE
Upgrade to .NET 4.5 and add async overloads

### ISSUE THREAD

**Issue by DarrellMozingo** [Pereingo/statsd-csharp-client#50]
The `Metrics.Time` methods should have `async` overloads. Requires upgrading the project to .NET 4.5. Not sure if .NET 3.5 is still worth supporting?

**Comment by AnthonySteele** [comment]
IMHO, yes you can safely upgrade the target .Net version to `4.5.2`.  I am doing similar on other libs.

`4.5.2` isn't even technically the latest version of .Net  any more, it's just [the stable one in long term support](http://www.infoq.com/news/2014/08/NET40-EOL)

If a client of this code is targeting .Net 4.0 or other older version, then you don't break their  code on the spot.  You just prevent them from updating this nuget package to the latest.  ... until they update their target to `4.5.2` or later, which is also fairly painless and worthwhile.

A good time to do this might be when the code is stable, and open issues seem to only relate to lack of support for `4.5.x` features ;)

**Comment by DarrellMozingo** [comment]
I do hate to make breaking changes, but that's a good point about doing it when issues are closed and people can just not upgrade if they're unable.

**Comment by AnthonySteele** [comment]
Absolutely. Also, version`4.5.2` is a good target at present - it's widely deployed, well road-tested, and it is in long term support. And we know there won't be a version 4.5.3.
