### ISSUE TITLE
Add TCP support

### ISSUE THREAD

**Issue by kobynet** [Pereingo/statsd-csharp-client#51]
Statsd server support tcp connection as well as udp. This is sometimes needed especially for accurate counters.

**Comment by DarrellMozingo** [comment]
Hi Koby,

Do you have a use case for this now? I know statsd itself supports it, but has always seemed like a shoehorned piece. For accurate counters like this you'd probably want a proper logging platform. If it's going over an unreliable network I'd suggest carbon-relay?

**Comment by kobynet** [comment]
https://github.com/etsy/statsd/issues/318 is a pretty good use case, especially when you do not have permission to change udp buffer size, and in general for sending big chunks (like Batched send etc.).

**Comment by pekiZG** [comment]
Is this "Up for grabs"?

**Comment by pekiZG** [comment]
@DarrellMozingo I had some free time and played around with it.
https://github.com/Pereingo/statsd-csharp-client/pull/59

**Comment by pekiZG** [comment]
Really close to being done with TCP support.
Could use second pair of eyes

**Comment by pekiZG** [comment]
Done
@kobynet and @DarrellMozingo 
take a look at https://github.com/Pereingo/statsd-csharp-client/pull/59 and leave a comment.

**Comment by pekiZG** [comment]
from [1.3.43](https://ci.appveyor.com/project/DarrellMozingo/statsd-csharp-client/build/1.3.43) version TCP client is available.

**Comment by DarrellMozingo** [comment]
Closed in #59 & live in 1.3.44. Thanks @pekiZG!
