### ISSUE TITLE
Async timer recording the wrong value

### ISSUE THREAD

**Issue by DarrellMozingo** [Pereingo/statsd-csharp-client#52]
Courtesy of @AnthonySteele...

Your code has:

``` c#
       public static T Time<T>(Func<T> func, string statName)
        {
            using (StartTimer(statName))
            {
                return func();
            }
        }
```

This will not do the right thing for async code, e.g. when the type T is actually "async Task<int>"
You will always record a time that is much shorter than the actual duration. In simple terms, you are recording the time taken to produce the Task<int>, not the time taken for the task to complete and produce the int.

The C# compiler generates a lot of code when there is an "await", this code is suspended, and resumes to do stuff when the task is actually complete. And without that "await"  you don't get this, you just time the production of the task.

You need an overload like this:

``` c#
       public static async Task<T> Time<T>(Func<Task<T>> func, string statName)
        {
            using (StartTimer(statName))
            {
                return await func();
            }
        }
```

I tested and confirmed this [here](https://github.com/justeat/JustEat.StatsD/blob/master/src/JustEat.StatsD.Tests/Extensions/ExtensionsTests.cs) and made code for it [here](https://github.com/justeat/JustEat.StatsD/blob/master/src/JustEat.StatsD/TimerExtensions.cs)

**Comment by AnthonySteele** [comment]
Thank you. 

PS: there is a DYAC error above: " this code suspected" should be "this code is suspended"

**Comment by DarrellMozingo** [comment]
Hmmmm... just realised this relates to (and is kind of the same thing as) issue #50, so requires a .NET version upgrade.

**Comment by AnthonySteele** [comment]
Good spot!

**Comment by DarrellMozingo** [comment]
Closing since #50 will get this issue as well
