### ISSUE TITLE
Will I violate any copyright laws if I fork this repo make some changes and publish as nuget ?

### ISSUE THREAD

**Issue by bilal-fazlani** [Pereingo/statsd-csharp-client#57]
I want to maintain a separate nuget project that is compatible for core clr. I read in the licence that I can publish this code. I just want to check with the owner. I will mention it in the description of package. Please let me know. Thanks !

**Comment by DarrellMozingo** [comment]
Hey Bilal,

I think you're well within your rights to fork and create a new repo - several others already have ([data dog](https://github.com/DataDog/dogstatsd-csharp-client), [high performance](https://github.com/Kyle2123/statsd-csharp-client), etc).

We've wanted to add .net core support & async to this one though so I'd really like to work with you to get them implemented in here. Are there other changes you're thinking about that might break the api or be a reason to fork?

**Comment by bilal-fazlani** [comment]
Thanks

I will be happy to work with you to add support for .net core to this project. Then there will be no need for me to maintain a separate project just for .net core.
