### ISSUE TITLE
Threading issues

### ISSUE THREAD

**Issue by bronumski** [Pereingo/statsd-csharp-client#61]
Having an issue where counters are sent from multiple threads on the same process and duplicate messages are being sent from one thread but the message from the other thread is not. I have switched to a fork which tackles this (https://github.com/Kyle2123/statsd-csharp-client) but it is not as up to date as you repo.

**Comment by pekiZG** [comment]
@bronumski what's the difference between Pereingo and Kyle2123 repos?
I took a peek at Kyle2123 repo. He is using .net 4 BlockingCollection.
As I understood this repo is targeting .net 2.0 and above.

Of course Pereingo could answer if it's possible to merge?

**Comment by DarrellMozingo** [comment]
The Kyle2123 is more of a true fork at this point. He added extra features we didn't want to add to ours. Are you able to reproduce this issue in a test @bronumski? Thanks!

**Comment by bronumski** [comment]
Hi guys, I am no longer working on the project at the moment and am in the middle of the move but as soon as the dust settles and providing I remember :) I will try and reproduce and knock up a test.

**Comment by pekiZG** [comment]
@bronumski we will ping you in a week or two :)

**Comment by pekiZG** [comment]
@bronumski how did the move went? Did you have time to reproduce this issue in a test?

**Comment by pekiZG** [comment]
@bronumski tracert

**Comment by DarrellMozingo** [comment]
Please re-open if you're able to reproduce, thanks!

**Comment by bronumski** [comment]
Hi @DarrellMozingo and @pekiZG,,

Sorry for the delay the move was crazy as was getting the green card. I have done very little development in the past few months and it has been difficult to get time to do anything.

I was able to reproduce the issue and I have some code to share with you. The code is a set of two tests, the first test is just a test on a single thread to prove the test mechanism works. The second test spins up x number of tests with y number of messages per thread. The test works by spinning up a udp endpoint which just shoves the message it receives into a list. The test is verified by waiting for all the expected messages to arrive and checks the count and the content to make sure all the messages are there.

[StatsDThreadingIssue.zip](https://github.com/Pereingo/statsd-csharp-client/files/795595/StatsDThreadingIssue.zip)

If you run the tests you will get intermittent results on the threaded tests. Occasionally they all pass but most of the time one or two fail as you can see from the following results. As you can see that some of the expected results are missing and some of the results are duplicated. I appreciate that there could be a flaw in the test however if you remove the statsdclient package and use the forked one all the tests pass. You may notice that with @Kyle2123 package the tests run slightly slower, that is because it is using the default buffering of messages before they are sent, this could be speed up but I wanted to keep the code identical for running the tests with both packages.

```
Uninstall-Package StatsdClient
Install-Package StatsdClient.HighPerformance
```
![capture](https://cloud.githubusercontent.com/assets/3909845/23245741/bfcc98ba-f943-11e6-8b63-61d8e11fb319.PNG)

**Running 4 threads with 1 message per thread**
```
Expected collection {
"myApp.prod.multi.thread.1.1:1|c", "myApp.prod.multi.thread.3.1:1|c",
"myApp.prod.multi.thread.3.1:1|c", "myApp.prod.multi.thread.4.1:1|c"
} to contain items {
"myApp.prod.multi.thread.1.1:1|c", "myApp.prod.multi.thread.2.1:1|c",
"myApp.prod.multi.thread.3.1:1|c", "myApp.prod.multi.thread.4.1:1|c"}

in order, but "myApp.prod.multi.thread.2.1:1|c" (index 1)
did not appear (in the right order).
```

**Running 5 threads with 5 messages per thread**
```
Expected collection {
"myApp.prod.multi.thread.1.1:1|c", "myApp.prod.multi.thread.1.2:1|c",
"myApp.prod.multi.thread.1.3:1|c", "myApp.prod.multi.thread.1.4:1|c",
"myApp.prod.multi.thread.1.5:1|c", "myApp.prod.multi.thread.2.1:1|c",
"myApp.prod.multi.thread.2.2:1|c", "myApp.prod.multi.thread.2.3:1|c",
"myApp.prod.multi.thread.2.4:1|c", "myApp.prod.multi.thread.2.5:1|c",
"myApp.prod.multi.thread.3.1:1|c", "myApp.prod.multi.thread.3.2:1|c",
"myApp.prod.multi.thread.3.2:1|c", "myApp.prod.multi.thread.3.3:1|c", 
"myApp.prod.multi.thread.3.4:1|c", "myApp.prod.multi.thread.3.5:1|c",
"myApp.prod.multi.thread.4.1:1|c", "myApp.prod.multi.thread.4.3:1|c",
"myApp.prod.multi.thread.4.4:1|c", "myApp.prod.multi.thread.4.5:1|c",
"myApp.prod.multi.thread.5.1:1|c", "myApp.prod.multi.thread.5.2:1|c",
"myApp.prod.multi.thread.5.3:1|c", "myApp.prod.multi.thread.5.4:1|c",
"myApp.prod.multi.thread.5.5:1|c"
} to contain items {
"myApp.prod.multi.thread.1.1:1|c", "myApp.prod.multi.thread.1.2:1|c",
"myApp.prod.multi.thread.1.3:1|c", "myApp.prod.multi.thread.1.4:1|c",
"myApp.prod.multi.thread.1.5:1|c", "myApp.prod.multi.thread.2.1:1|c",
"myApp.prod.multi.thread.2.2:1|c", "myApp.prod.multi.thread.2.3:1|c",
"myApp.prod.multi.thread.2.4:1|c", "myApp.prod.multi.thread.2.5:1|c",
"myApp.prod.multi.thread.3.1:1|c", "myApp.prod.multi.thread.3.2:1|c",
"myApp.prod.multi.thread.3.3:1|c", "myApp.prod.multi.thread.3.4:1|c",
"myApp.prod.multi.thread.3.5:1|c", "myApp.prod.multi.thread.4.1:1|c",
"myApp.prod.multi.thread.4.2:1|c", "myApp.prod.multi.thread.4.3:1|c",
"myApp.prod.multi.thread.4.4:1|c", "myApp.prod.multi.thread.4.5:1|c",
"myApp.prod.multi.thread.5.1:1|c", "myApp.prod.multi.thread.5.2:1|c",
"myApp.prod.multi.thread.5.3:1|c", "myApp.prod.multi.thread.5.4:1|c",
"myApp.prod.multi.thread.5.5:1|c"
} in order, but "myApp.prod.multi.thread.4.2:1|c" (index 16) did not appear (in the right order).
```

**Comment by DarrellMozingo** [comment]
I'll have a look soon, thanks for the follow up!

**Comment by DarrellMozingo** [comment]
Thanks for the bug report & following up on it @bronumski! Very much appreciated. I narrowed down the test and moved it into the main code base, as well as fixing the issues. We were testing thread safety for the `Add` operations but not `Send` :(

**Comment by DarrellMozingo** [comment]
This needed a breaking interface change btw, so it'll go out as a 3.x release today.
