### ISSUE TITLE
Disable the library when not needed at production environment

### ISSUE THREAD

**Issue by mayooran99** [Pereingo/statsd-csharp-client#62]
Is it possible to completely disable the library or even disable it at run time? This could come in handy when there is no need to run it at production in order to reduce the over head.

**Comment by pekiZG** [comment]
@mayooran99 I'm not sure if I understand the question.
Is it not possible to disable it via config?

**Comment by DarrellMozingo** [comment]
If you call `Metrics.Configure()` with a null/empty statsd hostname it will disable metrics being sent: https://github.com/Pereingo/statsd-csharp-client/blob/master/src/StatsdClient/Metrics.cs#L36

We commonly do this w/test environments (just don't provide a hostname in the config) so we don't get extra metrics.

Does that help?

**Comment by mayooran99** [comment]
Yes thanks!
