### ISSUE TITLE
2.0.68 nuspec file has improperly cased dependency for System.Net.NameResolution

### ISSUE THREAD

**Issue by mikemitchellrightside** [Pereingo/statsd-csharp-client#71]
It appears the nuspec file has the dependency for System.Net.NameResolution as system.net.nameresolution for .NETStandard1.3, and this causes issues when using this on a .net core application.

I've updated the nuget package locally to include this in the dependencies portion, and this works properly:
````    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard1.3">
        <dependency id="NETStandard.Library" version="[1.6.0, )" />
        <dependency id="System.Net.NameResolution" version="[4.0.0, )" />
      </group>
    </dependencies>
````

**Comment by DarrellMozingo** [comment]
Thanks @mikemitchellrightside. Would you mind doing a quick PR with the fix?

**Comment by mikemitchellrightside** [comment]
I would, but I don't see that the nuspec file is in the repository - so I'm not sure where or how it is being created.

**Comment by DarrellMozingo** [comment]
Looks like it gets generated from the `project.json` file :)  I fixed this and it'll go out in the next 3.x release in a few moments. Thanks again @mikemitchellrightside!
