### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by MichaelLogutov** [Pereingo/statsd-csharp-client#74]
Hello. Thank you for this great library.
Any plans to add async support for Send operations?

**Comment by DarrellMozingo** [comment]
Hey @MichaelLogutov! Thanks, glad you like it. No plans right now to add async support for sending, but I think it'd be relatively painless to do assuming the underlying libs support it. Would you be interested in taking it on and submitting a PR?

**Comment by DarrellMozingo** [comment]
Project deprecated, sorry. See the readme.
