### ISSUE TITLE
TCP Support does not allow sending of mulitple metrics

### ISSUE THREAD

**Issue by vinla** [Pereingo/statsd-csharp-client#75]
I noticed what appears to be a bug in the TCP sending mechanism. The send method disposes of the socket after sending any metric and hence any further metrics are not sent. This might be an issue with .Net core only as the Framework version only closes the socket.

**Comment by vinla** [comment]
Sorry, I've ditched the code, but essentially create a dotnet 2.x console app, include the library, configure to use TCP, then make any two metrics calls

**Comment by DarrellMozingo** [comment]
Project deprecated, sorry. See the readme.
